import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="grid grid-cols-2">
        <div>my logo</div>

        <div>custom nav to my links</div>
      </header>

      <main className={styles.main}>
        <h1 className="text-6xl text-center">lwTshort</h1>
        <h2>
          by{" "}
          <a href="https://github.com" className="text-violet-500">
            Leonardo Wiedemeier
          </a>
        </h2>

        <div className="mt-10">
          <form
            action="/api/upsert-url"
            method="POST"
            className="grid grid-cols-2 gap-4"
          >
            <input
              type="text"
              name="url"
              required
              placeholder="Enter your unbearingly long url"
              className="text-black"
            ></input>
            <input
              type="submit"
              value="Submit"
              className="bg-purple-500 hover:bg-purple-700 text-white py-2 px-4 rounded inline-flex items-center"
            />
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/assets/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
